server:
  port: 8090
#============== kafka ===================
kafka:
  consumer:
    zookeeper.connect: localhost:2181/kafka-one
    servers: localhost:9092
    enable.auto.commit: true
    session.timeout: 6000
    auto.commit.interval: 100
    auto.offset.reset: latest
    topic: test
    group.id: test
    concurrency: 2
  producer:
    servers: localhost:9092
    retries: 0
    batch.size: 4096
    linger: 1
    buffer.memory: 40960