spring:
  application:
    name: scloud-gateway
  port: 8888
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lowerCaseServiceId: true
      routes:
        - id:  scloud-product
          uri:  lb://SCLOUD-product
          predicates:
            - Path=/prodcut/**
          filters:
            - StripPrefix=1


eureka:
  client: # 客户端进行Eureka注册的配置
    service-url:
      defaultZone: http://admin:enjoy@eureka1:7001/eureka,http://admin:enjoy@eureka2:7002/eureka,http://admin:enjoy@eureka3:7003/eureka
#    register-with-eureka: true
  instance:
    instance-id: scloud-gateway
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 2 # 设置心跳的时间间隔（默认是30秒）
    lease-expiration-duration-in-seconds: 5 # 如果现在超过了5秒的间隔（默认是90秒）